from selenium import webdriver
import time

browser = webdriver.Chrome()
browser.get("localhost:7000")
browser.maximize_window()
browser.find_element_by_id('btn_register').click()
register_first_name = browser.find_element_by_id('first_name')
register_first_name.send_keys('test')
register_last_name = browser.find_element_by_id('last_name')
register_last_name.send_keys('ing')
register_email = browser.find_element_by_id('email')
register_email.send_keys('testing@gmail.com')
register_hierarchy = browser.find_element_by_id('hierarchy')
time.sleep(1)
register_hierarchy.send_keys('Jefe')
register_password = browser.find_element_by_id('password')
register_password.send_keys('pepe1234')
register_password_confirm = browser.find_element_by_id('password_confirm')
register_password_confirm.send_keys('pepe1234')
browser.find_element_by_id('btn_register').click()
time.sleep(1)
refill_email = browser.find_element_by_id('email')
refill_email.send_keys('totem@gmail.com')
refill_password = browser.find_element_by_id('password')
refill_password.send_keys('pepe1234')
browser.find_element_by_id('btn_login').click()
time.sleep(1)
browser.find_element_by_id('btn_drawer').click()
time.sleep(1)
browser.find_element_by_id('btn_patients').click()
time.sleep(1)
browser.find_element_by_id('btn_new_patient').click()
time.sleep(1)
patient_first_name = browser.find_element_by_id('first_name')
patient_first_name.send_keys('cacha')
patient_last_name = browser.find_element_by_id('last_name')
patient_last_name.send_keys('programador')
patient_dni = browser.find_element_by_id('dni')
patient_dni.send_keys(12345678)
patient_history = browser.find_element_by_id('history_number')
patient_history.send_keys('10')
patient_genero = browser.find_element_by_id('gender')
patient_genero.send_keys('Masculino')
browser.find_element_by_id('birth_date').click()
time.sleep(1)
fecha_table = browser.find_element_by_xpath('//tbody')
fecha_table.find_element_by_xpath('.//tr[1]/td[1]').click()
time.sleep(1)
browser.find_element_by_id('btn_submit').click()
time.sleep(1)
browser.find_element_by_id('btn_drawer').click()
time.sleep(1)
browser.find_element_by_id('btn_home').click()
time.sleep(1)
browser.find_element_by_id('btn_room_1').click()
time.sleep(1)
browser.find_element_by_id('btn_bed_1').click()
time.sleep(1)

time.sleep(3)
browser.close()
