from selenium import webdriver

browser = webdriver.Chrome()
browser.get("localhost:7000")
browser.maximize_window()
browser.find_element_by_id('btn_register').click()
register_first_name = browser.find_element_by_id('first_name')
register_first_name.send_keys('test')
register_last_name = browser.find_element_by_id('last_name')
register_last_name.send_keys('ing')
register_email = browser.find_element_by_id('email')
register_email.send_keys('testing@gmail.com')
register_hierarchy = browser.find_element_by_id('hierarchy')
register_hierarchy.send_keys('Jefe')
register_password = browser.find_element_by_id('password')
register_password.send_keys('pepe1234')
register_password_confirm = browser.find_element_by_id('password_confirm')
register_password_confirm.send_keys('pepe1234')
browser.find_element_by_id('btn_register').click()
refill_email = browser.find_element_by_id('email')
refill_email.send_keys('testing@gmail.com')
refill_password = browser.find_element_by_id('password')
refill_password.send_keys('pepe1234')
browser.find_element_by_id('btn_login').click()
browser.close()
