# Generated by Django 2.2.1 on 2019-05-15 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('history_number', models.PositiveIntegerField(blank=True)),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], validators=[django.core.validators.MaxValueValidator(1)])),
                ('income_diagnosis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
