# Generated by Django 2.2.2 on 2019-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='has_left',
            field=models.BooleanField(default=False),
        ),
    ]
