# Generated by Django 2.2.2 on 2019-09-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0002_progress_has_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='income_diagnosis',
        ),
    ]
