# Generated by Django 2.2.2 on 2019-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0003_remove_patient_income_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='income',
            field=models.BooleanField(default=False),
        ),
    ]
