# Generated by Django 2.2.2 on 2019-06-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0004_hospitalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patient',
        ),
    ]
