# Generated by Django 2.2.2 on 2019-10-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0004_progress_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
