# Generated by Django 2.2.2 on 2019-06-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0005_remove_bed_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Bien'), (1, 'Precaucion'), (2, 'Peligro')])),
            ],
            options={
                'verbose_name_plural': 'Progress',
            },
        ),
        migrations.AlterField(
            model_name='hospitalization',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='datient.Bed'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datient.Progress'),
        ),
    ]
