# Generated by Django 2.2.2 on 2019-10-20 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0005_doctor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
