# Generated by Django 2.2.2 on 2019-06-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0006_auto_20190617_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementaryStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='datient.Patient')),
            ],
        ),
    ]
