# Generated by Django 2.2.2 on 2019-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0007_complementarystudy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complementarystudy',
            options={'verbose_name_plural': 'Complementary Studies'},
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
