# Generated by Django 2.2.2 on 2019-08-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datient', '0008_auto_20190702_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
